fullname = "Nika Kobalia"
age = 17
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)