fullname = "luka dzagania"
age = 19
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)